apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mft-kube-deployment-dest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mqft-kube-dest
    spec:
      containers:
      - name: agentdest
        image: registry.eu-de.bluemix.net/mft-images/agentredist_mftimagerepo:1.0
        env:
        - name: MQ_QMGR_NAME
          value: "QM1"
        - name: MQ_QMGR_HOST
          value: "QMgr Host name"
        - name: MQ_QMGR_PORT
          value: "QMgr Port"
        - name: MQ_QMGR_CHL
          value: "QMgr SVRCONN Channel"
        - name: MFT_AGENT_NAME
          value: "AGENTDEST"
