apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mqadvmft-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mqadvmft
    spec:
      containers:
      - name: mqadvmft
        image: registry.eu-de.bluemix.net/mft-images/mqadvmft:1.0
        env:
        - name: LICENSE
          value: "accept"
        - name: MQ_QMGR_NAME
          value: "QM1"
