apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mft-cp4i-pba
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mqft-cp4i
    spec:
      containers:
      - name: agentpba
        image: image-registry.openshift-image-registry.svc:5000/mq915mft/mftpbaagent:1.0
        imagePullPolicy: Always
        env:
        - name: MQ_QMGR_NAME
          value: "mqmft0806"
        - name: MQ_QMGR_HOST
          value: "10.254.18.54"
        - name: MQ_QMGR_PORT
          value: "1414"
        - name: MQ_QMGR_CHL
          value: "DEV.ADMIN.SVRCONN"
        - name: MFT_AGENT_NAME
          value: "PBA"
        - name: IS_PBA_AGENT
          value: "true"
        - name: PROTOCOL_FILE_SERVER_TYPE # Required if IS_PBA_AGENT=true e.g.: FTP,SFTP,FTPS
          value: "SFTP"
        - name: SERVER_HOST_NAME # Required if IS_PBA_AGENT=true
          value: "10.254.18.31"
        - name: SERVER_PLATFORM # UNIX, WINDOWS - Required if IS_PBA_AGENT=true
          value: "UNIX"
        - name: SERVER_FILE_ENCODING # Required if IS_PBA_AGENT=true e.g.: UTF-8
          value: "UTF-8"
        - name: "MFT_TRANSFER_LOGS_ENABLED"
          value: "true"


